import './globals.css'
import { ReactNode } from 'react'
<<<<<<< HEAD
import {
  Roboto_Flex as Roboto,
  Bai_Jamjuree as BaiJamjuree,
} from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })

const baiJamjuree = BaiJamjuree({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-bai-jamjuree',
})

export const metadata = {
  title: 'NLW Spacetime',
  description:
    'Uma cápsula do tempo construída com React, Next.js, TailwindCSS e Typescript.',
=======
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> 7a56d27 (Aula 01)
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${roboto.variable} ${baiJamjuree.variable} bg-gray-900 font-sans text-gray-100`}
      >
        {children}
      </body>
=======
      <body className={inter.className}>{children}</body>
>>>>>>> 7a56d27 (Aula 01)
    </html>
  )
}
